- name: Prometheus metrics
  hosts: localhost
  sources:
    - cloin.eda.prometheus:
        prometheus_host: prometheus
        prometheus_port: 9090
        query: "up"
        interval: 5

  rules:
    - name: Debug metric
      condition: metric.resultType == "vector" and metric.up == 0
      action:
        debug:
